---
title: "Mainstreaming Race Science"
authors:
  - name: "Daniel J. Hicks"
    affiliation: 1
    corresponding_author: true
  - name: "Emilio Lobato"
    affiliation: 1
address:
  - code: 1
    address: "University of California, Merced"
corresponding_author: "Corresponding author: Daniel J. Hicks, dhicks4@ucmerced.edu."
abstract: |
  *[structured]*
acknowledgements: |
  *[strutured]* Thanks to Emily Merchant and John Jackson for some initial discussions that helped clarify the scope of the project and identify some key resources related to the Pioneer Fund and *Mankind Quarterly*.  Thanks to Anthony Sainez for help retrieving the *Mankind Quarterly* articles.  Thanks to Derek Devnich and James Dooley for their work attempting to secure the APA-published articles.  EL's work on this project was supported by UC Merced.  DH's work on this project was not supported by any specific funding. 
bibliography: "references.bib"
output: 
  # https://github.com/rstudio/rticles/pull/486
  # skeleton: <https://github.com/christopherkenny/rticles/tree/master/inst/rmarkdown/templates/science>
  # rticles::science_article:
  #   keep_tex: true
  #    move_figures: false
  #    draft: false
  #    number_sections: false
  bookdown::pdf_book:
    base_format: rticles::science_article
    keep_tex: true
    move_figures: false
    draft: false
    number_sections: false
---

<!-- 
Science submission instructions

General information: Research Articles
<https://www.science.org/content/page/science-information-authors>
- 5 printed pages in the journal
- 2000 to 3000 words of main text, in addition to an abstract, 3 to 5 display items (figures or tables) with brief legends, about 50 main-text references, and a structured acknowledgments section
- main text should be divided into sections with brief subheadings
- Materials and Methods should be included in supplementary materials and should be followed by additional data and figures needed to support the paper’s conclusions
- All data must be available in either the main text or the supplementary materials, or must be deposited at a publicly accessible repository and cited in the paper.

Initial submission
<https://www.science.org/content/page/instructions-preparing-initial-manuscript>
- Title: 96 characters
- Authors
- Affiliations:
- One Sentence Summary: 125 characters
- Abstract: Structured as BACKGROUND (1 sentence), OBJECTIVES/METHODS, RESULTS, CONCLUSION (1 sentence); 125 words or less
- Main Text:  The introduction should provide sufficient background information to make the article intelligible to readers in other disciplines and sufficient context so that the significance of the experimental findings is clear. Technical terms should be defined.
- References and Notes: There should be a single reference list that combines references cited in the main paper as well as those cited in the supplementary materials, and each reference should appear only once in the list. 
- Acknowledgements: Funding; Authors contributions (see link); Competing interests;  Data and materials availability
List of Supplementary Materials
- The width of figures, when printed, will usually be 5.7 cm (2.24 inches or 1 column), 12.1 cm (4.76 inches or 2 columns), or 18.4 cm (7.24 inches or 3 columns).

-->


# Introduction

*[hey you should read this paper]*

*[incorporate def'ns]*

scientific racism 
 ~ purporting to justify racial inequality and colonialism by appealing to the epistemic authority of science
 
race science
 ~ (pseudo-)scientific research that can be utilized for scientific racism
 
race science discourse
 ~ treating race science as a legitimate area of scientific research; this includes methodological critiques of race science and empirical tests that falsify race science hypotheses

*[Pioneer]*

*[probably don't include this]*
- pre-20th century history of race concepts and race science
- expansion and contraction of racialized terms over time


<!-- # Race science 1910-1960 -->

<!-- 
## The rise and fall of eugenics

*[write this]*

- scientific racism is thoroughly entangled with eugenics, but still conceptually distinct [@SlobodianUnequalMindHow2023]
    - sterilization laws focused on categories of criminality and mental ability, rather than race per se
    - contemporary defenders of eugenics at least sometimes claim to oppose racism 
    - claims of innate racial differences in intelligence can be made without dysgenic prophecies of a rapidly-expanding biological underclass

- 1910: Davenport founds Eugenics Records Office at Cold Spring Harbor
- 1926: NRC "Committee on the Negro" includes both Davenport and Boas: "neither was influential enough to veto his rival's participation" [@BarkanRetreatScientificRacism1992 113]
- 1930s: *Coming of Age in Samoa* [@MeadComingAgeSamoa1928] popularizes cultural anthropology, "free[ing] anthropology from the shackles of biology" [@BarkanRetreatScientificRacism1992 134]
- 1937: Pioneer Fund is founded to "support academic research and the \'[sic]dissemination of information, into the 'problem of heredity and eugenics' and 'the problems of race betterment'" [@MehlerFoundationFascismNew1989 21, quoting Laughlin]
- 1940: Carnegie Institute defunds Eugenics Records Office
- 1950: "For all practical social purposes 'race' is not so much a biological phenomenon as a social myth" [@BeagleholeRaceQuestion1950; though see @BrattainRaceRacismAntiracism2007]
 -->


# *Brown v Board* and *Mankind Quarterly*

Histories of scientific racism in the second half of the twentieth century have often emphasized the parascholarly journal *Mankind Quarterly* (MQ) \cite{
MehlerFoundationFascismNew1989,
WinstonScienceServiceFar1998,
SchafferScientificRacismAgain2007,
SainiSuperiorReturnRace2019,
WinstonScientificRacismNorth2020,
AdamsMisAppropriationBiological2021,
SainiDraperMillionsPhilanthropic2022
}, with or without its connections to PF. MQ was founded in 1960 by biologist R. Ruggles Gates (1882-1962), psychologist Henry Garrett (1894-1973), and non-academic anthropologist G. Robert Gayre (self-styled as "Gayre of Gayre and Nigg"; 1907-1996).  Gates' professional status was closely tied to eugenics and the explicit scientific racism of the 1920s, and he had been thoroughly marginalized in the wake of World War II \cite{WinstonScienceServiceFar1998}.  In contrast, Garrett had been president of the American Psychological Association in 1946 and chair of Psychology at Columbia from 1941 to 1955 *[cite]*.  

In the landmark case *Brown v Board of Education of Topeka* (1954), the US Supreme Court banned *de jure* educational segregation.  The Court's decision relied on expert testimony from psychologists and education researchers; but the segregationists had also put forward their own experts, including Henry Garrett \cite{WinstonScienceServiceFar1998, JacksonScienceSegregationRace2005, SchafferScientificRacismAgain2007}.  Shortly after *Brown*, Garrett left Columbia and became involved in segregationist and eugenicist efforts, and even the neofascist Northern League.  

As part of the segregationist reaction to *Brown*, MQ was created as what contemporary historians and philosophers of science call an "echo chamber" \cite{FernandezPintoKnowBetterNot2017}, a favorable venue for race scientists to publish their views, on the grounds that an "equalitarian dogma" created a censorious "taboo" against their research in mainstream publications \cite{TuckerFundingScientificRacism2002, JacksonMythicalTabooRace2020}.  Scholars have shown that echo chambers are a key part of the "tobacco strategy," used by numerous regulated industries — most infamously tobacco, but also fossil fuels and chemical manufacturing, among others — to "manufacture doubt" and delay regulation *[cites]*.  

In light of the origins of MQ, the significant attention paid to the journal by historians of scientific racism, and contemporary research on the "tobacco strategy," we hypothesized that bibliometric and text mining analyses would confirm that MQ functioned as an echo chamber for Pioneer-funded scientists.  This hypothesis was not supported.  Instead, mainstream psychology journals served as the echo chambers for race science.  




# *Mankind Quarterly* and Pioneer-funded researchers

We identified 16 researchers who had received funding from Pioneer; 14 of these researchers had profiles in the Web of Science (WoS) author search, allowing us identify 13 WoS-indexed journals that had published 6 or more of these authors. See Table \@ref(tab:researchers). 

| | | |
|:-----|-----:|----:|
| Thomas J. Bouchard, Jr. (1937-) | psychology | 184 |
| Brunetto Chiarelli (?-?) | anthropology | 91 |
| Hans Eysenck (1916-1997) | psychology | 661 |
| Robert A. Gordon (1932-) | sociology | 0|
| Linda Gottfredson (1947-) | psychology | 71 |
| Garrett Hardin (1915-2003) | ecology | 75 |
| Joseph M. Horn (1940-) | psychology | 68 |
| Lloyd Humphreys (1913-2003) | psychology | 0 |
| Arthur Jensen (1923-2003) | psychology | 235 |
| Michael Levin (1943-) | philosophy | 96 |
| Richard Lynn (1930-) | psychology | 288 |
| R. Travis Osborne (1913-2013) | psychology | 59 |
| J. Phillippe Rushton (1943-2012) | psychology | 277 |
| Audrey M. Shuey (1900-1977) | psychology | 10 |
| Philip A. Vernon (1950-) | psychology | 227 |
| Daniel Vining, Jr. (1944-) | demography | 33 |

Table: (\#tab:researchers) Pioneer-funded researchers.  Either identified in *[cite]* or named on Pioneer's website, along with birth and death dates from Wikipedia, identified discipline, and WoS author search result counts.  Brunetto Chiarelli does not have a Wikipedia page.  

![Journals publishing 6 or more Pioneer-funded researchers, Web of Science author search results *[date coverage]* (\#fig:wos)](img/wos_results.png){width="4.76in" height="2.6in"}

Figure \@ref(fig:wos) shows that, while MQ is among the "Pioneer-publishing" journals, a number of mainstream journals are more prominent: *Personality and Individual Differences* (PID), *Intelligence* (I), *Behavior Genetics* (BG), and *Psychological Reports* (PR).  In addition, only psychologist Richard Lynn appears to have published heavily in MQ.  Lynn has been an assistant editor of MQ since 1979 *[check this: https://rationalwiki.org/wiki/Mankind_Quarterly]* and president of PF since the death of psychologist J. Phillippe Rushton in 2012 *[cite]*.  By contrast, a number of Pioneer-funded researchers have published in PID, I, and to a lesser degree BG: Bouchard, Eysenck, Jensen, Rushton, Vernon, and also Lynn.  

*Personality and Individual Differences* (PID) was founded in 1980, with Eysenck as editor-in-chief and an editorial board including Jensen and Lynn. In the inaugural editorial, Eysenck identified "studies of the genetic determinants of individual differences in the areas of personality and intelligence" as one of the journal's eight major areas of interest.  Eysenck remained editor-in-chief until his death in 1997.  In 2005 the editorial board still included Jensen and Lynn. PID was first published by Pergamon Press, a mainstream academic press, and today is published by Elsevier.  According to the Scimago Journal Rankings, based on Scopus citation data, in 2022 PID had an H-index of 193, #29 in Psychology (Miscellaneous), and a 2-year citation index (impact factor) of 5.27, #24 in Psychology (Miscellaneous).  

*Intelligence* (I) was founded in 1977, with psychologist Douglas Detterman as editor-in-chief from the founding until 2016.  Lloyd Humphreys was on the editorial board starting from 1977; by 1990 he had been joined by Jensen and Philip Vernon.  Richard Lynn joined the editorial board sometime between 1998 and 2002.  (Archive copies of the I editorial board page are not available from the journal's website from 1999 through 2001.)  I has been criticized for including Lynn and Gerhard Meisenberg on its editorial board until July-August 2018 \cite{SainiSuperiorReturnRace2019}.  Meisenberg is also connected with the Pioneer Fund *[director?]*, and was editor-in-chief of MQ in 2015-18 *[check these]*.  I is published by Elsevier.  According to the Scimago Journal Rankings, based on Scopus citation data, in 2022 I had an H-index of 103, #32 in Experimental and Cognitive Psychology, and a 2-year citation index (impact factor) of 3.05, #31 in Experimental and Cognitive Psychology.  


# Topic model analysis identifies race science discourse

The fact that Pioneer-funded researchers published heavily in two mainstream psychology journals does not tell us anything about the content of their publications or the findings of their research.  We assembled a full-text corpus of articles published in MQ, PID, I, BG, PR, and Behavior and Brain Sciences (BBS) between 1960-2010 and used topic modeling to identify topics discussing race, intelligence, and both.  *[supplemental tables: Ns for each article, topic model parameters; supplemental figs: articles by pub over time, topic heatmaps, Silge plots, race-intelligence-both grids]*

![Silge plots \cite{SilgeTopicModeling2017} and smoothed time series for three focal topics.  Top row: top 15 terms by $\beta$ (term-topic distribution) for each topic.  Bottom row: count of articles associated with each topic, by journal and year.  Article counts use a threshold approach, with $\gamma$ (topic-document distribution) greater than 0.5.  Thin lines give annual values, thick lines give 5-year running averages.  Because *Behavior Genetics* and *Behavioral and Brain Sciences* are not prominent in any panel, neither is given a direct label. (\#fig:focal)](img/focal_topics.png){width="4.76in" height="3.57in"}

We focus here on three topics identified in one of the 24 fitted topic models; see Figure \@(fig:focal).  In this model, topic 07 is strongly associated with MQ:  MQ published dozens of articles in this topic each year, and no other journal ever published more than a handful, with most other journals publishing none in a given year.  The Silge plot \cite{SilgeTopicModeling2017} contains racial terms (`races`, `whites`, `negroes` and potentially `europe`, `africa`, `india`, and `japan`) as well as `book`, likely reflecting the fact that MQ published a number of book reviews while the psychology journals did not. 

Topic 22 is strongly associated with I and PID in the same way.  The Silge plot does contain `jensen`, as well as a reference to Raymond Cattell, who played a major role in the development of factor analysis and intelligence testing also advocated eugenics, fascism, and Nazi race science\cite{MehlerBeyondismRaymondCattell1997}. However, the other authors named in this topic — John Horn and Peter Bentler — do not appear to have contributed to race science discourse.  Instead this topic appears to identify "mainstream" (non-race science) intelligence research, specifically on factor analysis and the debate over whether intelligence in unidimensional or multidimensional.  (Three other topics only associated with mainstream intelligence journals and terms were also identified by this topic model.)  This topic indicates that the model is not simply lumping race science research together with other intelligence research.  

The Silge plot for topic 24, by contrast, suggests a distinct race science discourse topic, with multiple racial terms (`whites`, `blacks`, `racial_differences`, `races`, `race_differences`) and the names of three prominent Pioneer-funded researchers, `jensen`, `lynn`, and `rushton`.  To check this interpretation, we independently coded the top 121 papers in this topic (those with $gamma > 0.97$) as contributing to race science discourse or not.  105 (87%) were coded as race science discourse by both authors; 10 (8.3%) were coded as not race science discourse by both; and discordant codes were given to the remaining 6 (5.0%) (95% agreement, Cohen's $\kappa = 0.74$).  

In almost all years, most papers in topic 24 were published in mainstream journals rather than MQ.  Jensen's "How Much Can We Boost IQ and Scholastic Achievement?" \cite{JensenHowMuchCan1969} was published in 1969 in Harvard Educational Review (not included in this study), and the time series indicates that, around this time, there was an increase in articles in topic 24 in both PS and MQ (the only two journals in our corpus that were active at the time).  MQ shows another sharp increase in the late 1970s, around the time Lynn was brought on as assistant editor, *[confirming the claim that Lynn shifted MQ's focus to intelligence research]*.  PID published multiple papers in topic 24 almost immediately after it was founded, with I showing a more gradual increase between the mid-1970s and mid-1990s.  

# Race science and behavior genetics

Notably, BG published very few articles in this topic.  Outside of the field itself, behavior genetics is strongly associated with race science by both other academics and the general public.  Panofsky \cite{PanofskyMisbehavingScienceControversy2014} argues that, prior to Jensen's 1969 paper, behavior genetics emphasized the study of non-human animals and intentionally avoided associations with eugenics and public controversy more generally.  In response to Jensen, critics such as Lewontin offered broad critiques of behavior genetics as such, and behavior geneticists in turn adopted a radical conception of academic freedom (without any sense of responsibility for the social implications of academic research) and a siege or wartime mentality, as demonstrated by Sandra Scarr's 1986 presidential address to the Behavior Genetics Association (BGA) \cite{ScarrThreeCheersBehavior1987}.  Scarr's address coincided with the period between 1970-1990 when BG published articles in topic 24 (including Scarr's address itself). 

However, Glayde Whitney's 1995 BGA presidential address was published in MQ rather than BG.  According to Whitney, BG's editor refused to publish the address and the BGA Executive Committee (except for Whitney himself) voted to "issue an official statement of denouncement" of the address; though we were unable to find any such a statement, and Panofsky reports that "nothing official was done to Whitney."  In his address, Whitney criticized "the Marxist-Lysenkoist denial of genetics"; quoted Peter Brimelow — a white nationalist and later founder of the racist and xenophobic website VDARE — defining "racist" as "anyone who is winning an argument with a liberal"; and proposed as a "reasonable scientific hypothesis" that differences in murder rates between countries and cities was caused by racial genetic differences in intelligence, empathy, aggression, and impulsivity.  

The topic model analysis and the case of Whitney's address suggest that, by the 1990s, behavior genetics may have somewhat distanced itself from race science, though perhaps without directly repudiating it \cite{GillbornSoftlySoftlyGenetics2016, HennWhyDNANo2021}.  

*[move most of this to supplement?]*
To check this interpretation, we ran an independent search for documents with the keywords "race" and "intelligence" published in BG from 1972 to 2020, using Springer's journal search website.  This search returned 125 documents.  33 were presentation abstracts from meetings of the Behavior Genetics Association; we did not examine these further.  14 of the remaining documents were published since 2010 (after the scope of the primary study).  Among these, one obituary and two papers celebrated the work of John Loehlin, a prominent race-and-intelligence researcher who had been Director of the American Eugenics Society from 1968-1972 \cite{JohnLoehlin19262020, WaldmanIntroductionFestschriftJohn2014, PlominGenotypeEnvironmentCorrelationEra2014}.  Another was a retrospective of the work of Lindon Eaves, a geneticist who made at least one notable contribution to debates on the Scarr-Rowe hypothesis (interactions between heritability, race, and class).  None of these 14 documents reported any studies of racial differences.  

28 documents in this sample were published between 1990 and 2010.  One was an obituary of Jerry Hirsch, a critic of hereditarianism in general and Jensen in particular \cite{RoubertouxJerryHirsch202008}, and another was an obituary of David Rowe \cite{RodgersObituaryDavidChristian2003}.  Only 2 of these 28 documents reported race differences of any kind: one examining at interactions among race, sex, and heritability for adolescent BMI (Body Mass Index, used as a measure of overweight/obesity) \cite{JacobsonGeneticSharedEnvironmental1998}; and the other at interactions among race, family history of alcoholism, and visuospatial performance \cite{BermanReducedVisuospatialPerformance1995}.  Finally, Philip Vernon — one of the Pioneer-funded scientists we identified earlier — published a critical review of a book that attempted to address hereditarianism, the Flynn effect, race-and-intelligence research, and some related issues.  

This supplemental review provides additional support for the interpretation that behavior genetics had distanced itself from race science by the 1990s.  Notably, this review brought our attention to a disciplinary history of behavior genetics published in 2010 \cite{McGueEndBehavioralGenetics2010}, which acknowledges the historical association with eugenics but does not mention Jensen and other race science controversies since World War II. Instead postwar behavior genetics is portrayed as an endeavor to counterbalance the hegemony of the "Blank Slate," the supposedly widespread view that genetic differences play no role in explaining individual differences \cite{BatesonCorpseWearisomeDebate2002}. And none of the three documents celebrating Loehlin noted his postwar involvement in the eugenics movement.  None of the documents examined in this supplemental review explicitly repudiate race science.  Similarly, another disciplinary history of behavior genetics, published by Plomin in 2023 \cite{PlominCelebratingCenturyResearch2023}, briefly mentions the controversies surrounding Jensen's 1969 paper and later *The Bell Curve*, writing that Jensen's work was controversial because he "touched on ethnic differences"; though ultimately Plomin reassures the reader that "by the 1990s, quantitative genetic research had convinced most scientists of the importance of genetics for behavioral traits, including intelligence."  In short, behavior geneticists seem to typically adopt a posture of objectivity and technical rigor, downplaying the extent of the field's involvement in race science in the past, and displacing the source of race science controversies to external, "political," and "irrational" actors.  




# Discussion

Our findings indicate that *Mankind Quarterly* (MQ) was less important as an echo chamber for late 20th century race science than mainstream psychology journals, especially *Intelligence* (I) and *Personality and Individual Differences* (PID).  Indeed, MQ published a very different kind of race science from the race-and-intelligence research published in I and PID, even after *[Lynn joined the MQ editorial board]*.  

*[for discussion: the possibility for white supremacist appropriation, ie, race science done by scientists who are not themselves scientific racists: CarlsonQuantifyingContextualizingImpact2020; probably some reviews of Paige Harden; O'Connor and Weatherall]*


We stress that we are not identifying any particular scientist as a racist, scientific racist, or race scientist based on the topic model results.  Scientific research can be utilized to promote scientific racism — and thus count as race science — independently of the views and attitudes of the scientist who conducted that research.\cite{TaberyWhyStudyingGenetics2015, GillbornSoftlySoftlyGenetics2016, CarlsonQuantifyingContextualizingImpact2020, HennWhyDNANo2021}  But this does not mean that scientists are not responsible for the downstream social effects of their 
research, even when these effects involve deliberate misinterpretation.*[Douglas, Kitcher, Kourany, Havstad; Block and Dworkin?]*  Like other citizens, scientists are responsible for mitigating the reasonably foreseen harms that result from their actions.  And we now have decades of empirical evidence that research on the genetics of intelligence — even research that does not itself touch on race — can and will be used to promote scientific racism \cite{MeyerWrestlingSocialBehavioral2023}.  Specifically, while our findings suggest that behavior genetics has attempted to distance itself from scientific racism, behavior genetics research — and research on human genetics more generally — may be especially susceptible to appropriation by scientific racists \cite{CarlsonQuantifyingContextualizingImpact2020, OgbunugaforDNABasketballBirthday2022}.  A colorblind attitude of "we don't talk about race anymore" *[cite Bonilla-Silva?]* is likely insufficient to prevent particular research findings being utilized as race science. 


Our distinction between race science and race science discourse highlights an important "engagement dilemma" for scientists challenging race science and scientific racism.  While the "tobacco strategy" for manufacturing doubt involves targeting mainstream scientists and promoting fringe scientific views, its primary audiences are lawmakers and the general public.  The aim of the strategy is not to change the opinion of mainstream scientists, but instead to cultivate the impression that there is legitimate scientific uncertainty about the issue, reasonable disagreement among qualified experts *[cites]*.  On the one hand, refusing to engage with fringe scientists — or, often, pseudoscientists \cite{BhakthavatsalamVirtueEpistemologicalApproach2021} — means that false or misleading statements go unchallenged.  On the other hand, detailed, technical criticism legitimizes the fringe views, creating exactly the impression of reasonable scientific disagreement that the tobacco strategy is intended to produce.  

In the case of race science, mainstream psychologists have often taken a non-engagement approach — whether due to a strong conception of academic freedom or a desire to avoid stoking controversy — with the result that race scientists have been able to present themselves as the representatives of "mainstream science on intelligence."  On the other hand, critics — most prominently Gould, Kamin, and Lewontin — have offered sophisticated technical critiques.  But these tend to spiral off into esoteric debates that are inaccessible to the general public, as with "Lewontin's fallacy" \cite{RosemanLewontinDidNot2021}.  Consequently these critiques are likely to be either ignored by the general public or taken as evidence of legitimate scientific debate.  
*[more?]*


## Limitations

A key limitation of the current study stems from the inability of text mining techniques to draw on a broader cultural context than what is represented in the corpus.  Scholars of racism and US race relations have noted a shift in the way racist attitudes are understood and expressed, from *[something]* to "colorblind racism" *[Bonilla-Silva]*, defined as *[defn]*.  Colorblind racism involves the use of racialized "codes" or "dogwhistles," language that is superficially non-racial but carries racial implications, such as (in the US context) "violent inner city criminals" or "welfare queen" \cite{SaulDogwhistlesPoliticalManipulation2018}.  Alderfer notes that the racist implications of *The Bell Curve* only emerge gradually, with the opening of the book using the colorblind language of "group differences" \cite{AlderferScienceNonsciencePsychologists2003}.  Panofsky et al. show how the term "human biodiversity," originally developed for anti-racist purposes by biological anthropologist Jonathan Marks, has been inverted by white supremacists and is now a dogwhistle for biological racial hierarchy \cite{PanofskyHowWhiteNationalists2021}.  These cases suggest further that colorblindness can facilitate white supremacist appropriation of non-racial research — even contrary to the researchers' own intentions — as scientific racist readers re-interpret racial-neutral language as dogwhistles \cite{GillbornSoftlySoftlyGenetics2016, WillsAreClustersRaces2017}.  

Techniques such as topic modeling may be able to account for discursive shifts from explicit to coded racial language, but only if the corpus contains a critical mass of documents using both sets of terms together.  This would seem to require either a relatively gradual transition, the inclusion of reflective commentary, such as scholarship identifying and analyzing the transition, or both.  It is unlikely that these requirements are met by the corpus used in this study.  So it is plausible that the topic models used here have some rate of "false negatives," documents in the corpus that engage in race science discourse but in a colorblind way that avoids the use of the explicit racial terms in the race-and-intelligence topic.  

The phenomenon of colorblind racism is closed related to ambiguities that cannot be resolved even by human coders familiar with the broader cultural context.  Two relevant examples are the "Flynn effect," a secular increase in intelligence test scores noted by philosopher James Flynn; and studies of "national IQ," exemplified by the work of Richard Lynn.  The Flynn effect implies that environmental factors can create group differences in IQ that are comparable to Black-White differences, and thus directly challenges claims that the racial differences are biological.  Using methods widely regarded as ad hoc, cherry-picking, and generally unreliable, Lynn and collaborators have claimed that national IQ averages are correlated with national GDP.  Both the Flynn effect and "national IQ" are strongly associated with race-and-intelligence discourse in the US cultural context.  But scientific journal articles on these topics may not include any racial language at all.  For example, a meta-analysis of the Flynn effect does not discuss racial differences or use terms such as "White" or "Black" outside the reference list \cite{TrahanFlynnEffectMetaanalysis2014}.  Should such articles be coded as race science discourse?  We expect that even readers who accept our definitions of race science and race science discourse will reasonably disagree on how to answer this question.  Topic models, of course, are not even capable of representing this essential ambiguity.  





<!--
*[replace w/: WinstonWhyMainstreamResearch2020: race science as a community project of psychology(?).  radical academic freedom is a tool used to defend race science PigliucciWhatAreWe2013, RosemanTroublesomeReflectionRacism2014, LarsenMoreProvocativeLess2020.  an important part of how these mainstream journals function as race science echo chambers.]*

Proponents of a strong conception of academic freedom often point to chapter 2 of philosopher John Stuart Mill's *On Liberty* \cite{MillLiberty1862}, "Of the Liberty of Thought and Discussion."  However, in chapter 1 of the same book, Mill states the Harm Principle as the overall thesis of his book: "The only end for which people are entitled, individually or collectively, to interfere with the liberty of action of any of their number is self-protection. The only purpose for which power can be rightfully exercised over any member of a civilized community, against his will, is to prevent harm to others." Even for Mill, free speech and free inquiry are appropriately restrained when the ideas in question will harm others.  

More recently, philosopher Shannon Dea \cite{DeaEvolvingSocialPurpose2021} has argued that academic freedom is importantly distinct from freedom of speech.  Whereas freedom of speech is universal, enjoyed by all residents of countries where speech is legally protected, academic freedom is more exclusive, enjoyed only by college and university faculty.  (Though, as Dea points out, non-tenure-track faculty often do not have effective protections for academic freedom.)  Freedom of speech primarily serves to protect the interests of the individual speaker: that you will not be punished by the state for stating unpopular opinions.  But academic freedom is "other-directed," primarily serving to benefit the common good of society as a whole by enabling the pursuit of truth.  

Advocates of research on genetics and intelligence — both anti-racist liberals and race scientists — claim this work will lead to social benefits.  This reflects a recognition that the purpose of academic freedom is to promote the common good, rather than merely satisfy an individual's curiosity.  But the promised benefits are either vague or do not actually require understanding the genetics of intelligence.\cite{KaplanGaltonQuincunxProbabilistic2021, CoopLotteryLuckLegacy2022}  

[EL notes on academic freedom as simply one value in science:

Other ethical values that guide scientific research have been institutionalized via documents such as The Belmont Report. Principle values described in The Belmont Report are intended as guides and regulations of scientific researchers' behavior so as not to infringe on the rights or liberties of human study volunteers. This report was written in response to revelations in the 1970s of the Tuskegee Syphilis Study, wherein researchers at the CDC and HHS lied to participants - all of whom were impoversiehd black men - about the nature of the study and whether or not they had tested positive for syphilis, coerced their participation with extravagant compensation, and refused to allow men infected with syphilis to be treated at all. The Belmont Report outlines values guiding scientific research that focus on respect for persons, beneficence, and justice: 
Respect for persons - informed consent, participants are individuals with agency. 
Beneficience - very much like Hippocratic "do no harm" or, if harm is unavoidable, the potential harms are outweighed by the benefits of research. 
Justice - no population should disproportionately bear the burdens of being investigated scientifically; do not sample merely from convenient populations; when advances are made due to public funds (e.g. taxpayer money) the products of such advances are not restricted only to those who can afford them.

How does race science research square against these other values in scientific research? Are participants ever honestly informed that they are (or were, in the case of a debriefing form) being evaluated to see which demographics are superior/inferior to which other ones? Granted, the Belmont Report is US-specific, but comparable other documents, regulations, or laws exist around the world that promote similar values. e.g. The Declaration of Helsinki states that the pursuit of knowledge cannot be used to trample on the rights of research participants.

Maybe brief discussion of Mertonian Norms? Seems that race science research violates the norms of Universalism, Disinterestedness, and Organized Skepticism. Granted, most of the scientific community in practice violates all of the norms pretty frequently, so maybe this isn't a strong point to include.

Recently published paper by Zivony et al in PLOS Computational Biology - "Ten simple rules for socially responsible science" - The authors call out a variety of biases in research (extreme male brain hypothesis of autism; face recognition software trained only on white faces; race differences in test scores) as failing to appropriately limit inferences based on the research's design or failing to properly ground their research in social theory or relevant historical context.

Random oOther thought: academic freedom doesn't mean being free from criticism of one's methods, intentions, or theoretical starting point. Unless someone is calling for an academic policy that forbids race science as an academic area of inquiry, talk of academic freedom is non sequitor. Pointing out flaws in research and concluding the research is therefore wasted time/resources is not a threat to academic freedom. No one has forbidden research on geocentrism, but we've recognized for a few centuries now that it's a waste of time to pursue that line of inquiry.

]

-->




*[what can science do? Posselt, /Equity in Science/]*

*[max ~50 refs]*


\appendix
# Materials and methods

*[probably some introduction]*

## Corpus assembly

Corpus assembly is summarized in figure *[xref]*.  The corpus was assembled in two parts, one for *Mankind Quarterly* and the other for mainstream journals.  

*[figure]*

### Mankind Quarterly

An electronic archive of *Mankind Quarterly*, from the first issue in *[1969]* through 2004, is available for free on the open web from *The Unz Review*, which has been characterized as a white nationalist website by the Southern Poverty Law Center *[<https://www.splcenter.org/hatewatch/2021/01/19/meet-white-nationalist-organizer-who-spewed-hate-against-lawmakers>]*.  Web scraping packages and techniques *[which?]* were used to retrieve every PDF available in this archive.  These PDFs were processed using the open-source OCR (optical character recognition) software `tesseract` and the R API `rtesseract` *[cites]*.  This stage of corpus assembly was conducted in Fall 2021.  

### Mainstream journals

To identify suitable mainstream journals for inclusion in the corpus, we first identified academic researchers who had been funded by the Pioneer Fund.  Pioneer is an American non-profit organization founded in 1937 to fund eugenics research *[cite]*.  After the *Brown v. Board of Education* ruling in 1954, Pioneer funded various segregationist efforts across the United States.  *[Shockley and Jensen]*.  We reviewed a critical profile of Pioneer *[cite]* as well as an archived page from the organization's own web site *[cite]*, which together listed 16 researchers who had received Pioneer funds.  

We then used the author search tool in Clarivate's Web of Science platform *[url]*, retrieving publication lists for 14 researchers.  These searches were conducted between 2021-09-24 and 2021-10-05 by DJH.  After parsing these results, we counted how many of the 14 researchers had published in each journal.  13 journals had published 6 or more of the 14 Pioneer-funded researchers.  We excluded *Mankind Quarterly* (as already included) as well as *Science* and *Nature* (as too general) from further consideration in this side of the corpus.  3 journals published by the American Psychological Association (APA; *American Psychologist*, *Contemporary Psychology*, and *Journal of Educational Psychology*) had to be excluded due to confusion over who could give us permission to use the archives for a text mining project, with both APA and ProQuest asserting that we needed to get permission from the other entity.  *European Journal of Personality*, published by SAGE, also had to be excluded because our institutional access only went back to 1999.  

The remaining 5 journals are all published by major academic publishers — Elsevier, Springer, or Cambridge University Press — and each item in the entire run of each journal has been assigned a DOI (digital object identifier) for archival purposes.  We used the Crossref API and `rcrossref` R interface to this API *[cite]* to retrieve metadata for each item published from 1960-2010 in each of these 6 journals.  These metadata included item-level license information — confirming that the text of each item could be used for text mining projects — and a URL to an electronic version of the item.  These URLs were used to retrieve an HTML or PDF version of each item, except for *Personality and Individual Differences*.  This journal has published a relatively large number of non-article documents, such as book reviews and commentaries, which are not available at the URL included in the Crossref metadata.  (This is unfortunate, as it was not difficult to find highly relevant documents that we could not automatically retrieve and therefore excluded from our corpus *[review]*.)  Instead we used Elsevier's ScienceDirect API *[url]* to search and retrieve all items from *Personality and Individual Differences* that are available.  PDFs were run through OCR and text extraction as necessary, as with the *Mankind Quarterly* documents.  

All together, *[corpus summary, total and by journal; table]*

## Text preparation

After document retrieval and text extraction, we pre-processed the text using the `spaCy` NLP (natural language processing) Python library and the R API `spacyr` *[version, cites]*.  Specifically, we applied regular expressions to remove header/footer copyright notices and hyphenation, used spaCy to annotate and extract noun phrases (eg, "the intelligence test items"), and then cleaned and standardized these phrases (eg, removing the/an/a, coverting all text to lowercase, and replacing all whitespace with underscores: "intelligence_test_items").  We then counted the occurrence of each noun phrase in the document.  The aggregated "document-term matrix" was stored in Parquet format *[cite]* for performance reasons, and written and read using the `arrow` package for R *[cite]*.  *[availability]*

NLP-extracted noun phrases offer a number of advantages over the more traditional unigram ("single-word") tokens.  First, noun phrase extraction removes many standard stopwords (articles, common verbs) without relying on a fixed, a priori stopword list.  Phrases can be more informative than single terms, for example, distinguishing "intelligence test" from "hypothesis test."  But simple n-gram extraction will include numerous phrases that are not especially meaningful.  Consider the sentence "Since our first analyses of feeding patterns in rats, we had been using a criterion of 40 minutes (Le Magnen & Tallon 1963; 1966)" *[10.1017__^__s0140525x0000042x]*.  Bigrams such as "since our" and "criterion 40" will likely be discarded in vocabulary selection, but significantly increase the computational cost of vocabulary selection.  Noun phrase extraction is therefore more efficient.  

After noun phrase extraction, the corpus comprised *[tokens]* of *[distinct noun phrases]*.  

### Data and code availability

Document metadata retrieved from Crossref does not appear to be covered by any copyright or other intellectual property restrictions.  However, due to copyright restrictions, we are unable to make document fulltext or Web of Science search results publicly available.  Code for the corpus assembly and text preparation steps described above is available by request. 

The public analysis repository, <https://github.com/dhicks/race-science> *[DOI]*, includes document metadata and documentwise counts of NLP-extracted noun phrases ("document-term matrices"), along with code to reproduce the analysis of the following sections.  *[repo readme: requires R 4.1.2; rig (<https://github.com/r-lib/rig/>) for managing multiple R installations]*


## Vocabulary selection

We took an information-theoretic approach to vocabulary selection.  Consider a game in which I draw a document from the corpus, then a single token from that document.  I tell you the term, and you have to guess which document I picked.  Intuitively, highly informative terms (in this project, noun phrase types) are distinctive, allowing you to dramatically narrow down the list of potential documents.  This "informativeness" of a term can be quantified as the KL (Kullback-Leibler) divergence from a "baseline" distribution of documents to the distribution conditional on the term.  Because the most informative terms tend to be typos and OCR errors — these are unique to a single document — we multiply the KL divergence by the logarithm of the total number of occurrences of the term across the entire corpus.  We refer to the resulting measure as $log(n) \Delta H$ or simply `ndH`. 

*[Hicks 2021?]* used the `ndH` approach in a topic modeling analysis, where the baseline distribution was the uniform distribution across documents.  In the current project, we found that this approach heavily favored recurrent noun phrases in the longest documents.  Many of the documents published in *Psychological Reports* are extremely short, 1-2 reports of a single study; while many of the documents published in *Brain and Behavioral Sciences* are book-length collections that include a long review article and sometimes dozens of commentaries.  Very generic noun phrases that happen to appear in the latter can occur orders of magnitude more often than highly distinctive phrases in the former, and so the $log(n)$ factor overwhelms the $\Delta H$ factor.  

To address this, we used a different baseline distribution of documents, namely, one in which document probability is proportional to length.  This makes phrases from short documents much more "surprising" (much less likely to occur according to the baseline), and hence substantially increases their informativeness.  This was more effective at identifying useful phrases from across the corpus.  

A common rule of thumb in topic modeling is that the vocabulary should have about 10 times as many distinct terms as the number of documents in the corpus *[cite]*.  However, we had some concerns with computational demands here:  the resulting document-term matrix would have roughly $10 \times 33,000^2$ or 10.9 billion entries; with 10% density this would require on the order of 4 GB of memory just for a single copy of the matrix; and most of the analysis was to be conducted on the authors' laptops.  We therefore chose to work with three smaller vocabularies, $5 \times$, $1 \times$ and $\frac{1/5} \times$ the number of documents.  We refer to these as the "large," "medium," and "small" vocabulary, respectively, and they include *[counts]* distinct phrases.  We compare findings across vocabularies as a robustness check.  


## Topic modeling

To fit topic models, we followed the approach proposed by *[cite]*, which uses varimax-rotated partial principal components instead of the variational inference methods used by standard topic model packages *[eg, stm]*.  This novel approach was implemented in the R package `tmfast`, *[cite]*.  A simulation study of `tmfast` found that it was significantly faster and only slightly less accurate at reconstructing known word-topic and topic-document distributions, compared to the standard topic modeling package `stm`.  

Topic models were fit for all three vocabularies (large, medium, and small) with $k = 5, 10, 20, 30, 40, 50$ (number of topics), resulting in a total of 18 models. 

Following the approach of *[Hicks 2021?]*, we did not attempt to identify a unique best model for further analysis.  While we focus on the medium vocabulary, $k=30$ model as the "median" among the 18 models fit, we compare and contrast findings from this model with those from the other models.  


### Topic model interpretation

After fitting topic models, our first research question was whether we could identify distinctive "race science" topics.  We addressed this question in two ways.  Following common practice in topic modeling, we extracted lists of the top $n$ (highest-probability) terms (noun phrases) from each topic in each model, with $n$ generally ranging between 5 and 15 as we explored the models.  *[tables + Silge plots]*  

*[drop]*
We also adapted the "discursive space" analysis proposed by *[Hicks 2021?]*.  This analysis combines the Hellinger distance between topic-document distributions — capturing how "far apart" two documents are — with dimensional reduction techniques used for data visualization.  This produces a two-dimensional visualization of individual documents, arranged so that documents with similar topic distributions are visually clustered and visually distinct from documents with different topic distributions.  *[availability]*

Specifically, for each fitted topic model, we extracted topic-document distributions for each document and calculated pairwise Hellinger distances.  We then processed these distances using the UMAP algorithm for dimension reduction, as implemented in the `umap` package *[details; cite]*.  To reduce computational requirements for these steps, we first dropped documents published in the journal *[Psychological Reports]* (*[x documents removed, y remaining]*; note that the full corpus was used to fit the topic models, *Psychological Reports* was removed just for this visualization).  Using the `plotly` library *[cite]*, we construct an interactive visualization:  each point represents a single document, and points can be colored based on either their journal or highest-probability topic.  Tooltips are displayed when we hover over a point, including document metadata (title, journal, authors, year) as well as "key phrases."  

To calculate key phrases for a given document $d$, we first identified the highest-probability topic $t$ for that document and the word-topic (noun phrase-topic) distribution $\beta_{w,t}$ for that topic.  We also retrieved the document-term matrix, containing the count $n_{w,d}$ of occurrences for each word (noun phrase), and calculated a weighting $n_{w,d} \beta_{w,t}$ for each word.  The key phrases are the 5 most highly-weighted terms for the given document.  

### Topic quality assessment
*[rewrite]*

We next conducted a topic quality check of topic 19 from the medium vocabulary, $k=30$ model.  Keyword and inspection of the UMAP interactives seemed to indicate that this topic was a "race science discourse" topic in this model.  

To confirm this initial impression, a spreadsheet of all articles with $\gamma > 0.25$ for this topic was extracted (excluding articles published in *Psychological Reports*), and the top 200 articles were reviewed manually by both authors.  For this qualitative analysis, we defined *scientific racism* as (purporting) to justify racial inequality and colonialism by appealing to the epistemic authority of science; *race science* as (pseudo-)scientific research that can be utilized for scientific racism; and *race science discourse* as treating race science as a legitimate area of scientific research; this includes methodological critiques of race science and empirical tests that falsify race science hypotheses.  Our qualitative review of the top-200 topic-19 articles focused on classifying them as *race science discourse*.  

For the first round of review, both authors worked independently,  dichotomously coding each article as race science discourse or not.  We calculated the "false positive rate" — documents with a very high $\gamma$ in this topic that were not race science discourse — and interrater reliability using Cohen's $\kappa$.  
*[false positive rate]* 
*[Initial interrater reliability was low, $\kappa = 0.4$, with 50 out of 200 articles classified discordantly.]*  To understand the disagreement, both authors examined the 50 discordant articles using an interactive grounded theory approach.  After this process, some initial codings were changed and *[almost]* all of the remaining *[n]* discordant articles were coded as follows:  

hereditarianism and/or eugenics
 ~ 29 papers.  On the “eugenics” side, mostly examines or otherwise discusses the "dysgenic" claim that "low-intelligence" people have more children than "high-intelligence" people.  The “hereditarianism” side is more varied, with papers on environmentalist interventions to raise IQ, genetics of IQ, and several other sub-topics.  

Flynn effect 
 ~ 15 papers.  Supporting, challenging, or otherwise focusing on Flynn’s findings that IQ has increased over time. 

Lynn/national IQ
 ~ 3 papers.  Supports, challenges, or focuses on international IQ data/comparisons made by Richard Lynn. 

We agreed that, for all three categories of papers, there was reasonable ambiguity about whether they should be classified as race science discourse.  These papers either do not explicitly mention race, or do so with just a brief mention of the "race and intelligence controversy."  On the other hand, they either contribute to or legitimatize areas of research that are deeply entangled with race science, and might thereby contribute to public perceptions of a legitimate scientific debate about race and intelligence.  

Based on this qualitative review, we judged that the topic model approach was sufficiently sensitive (low "false positive" rate) in identifying race science discourse. 

